// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qugiphjvimtkzoewgjyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Z2lwaGp2aW10a3pvZXdnanl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDQ4OTksImV4cCI6MjA2NDI4MDg5OX0.DF0XnUWENkwa4mkvPalqziYV-vwRyJ88ISxVqCrGuP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);